---
repos:
  - repo: https://github.com/dadav/helm-schema
    rev: 0.14.1
    hooks:
      - id: helm-schema
        # for all available options: helm-schema -h
        args:
          # directory to search recursively within for charts
          - --chart-search-root=.
          - --add-schema-reference
          # don't analyze dependencies
          - --no-dependencies

          # add references to values file if not exist
          - --add-schema-reference

          # list of fields to skip from being created by default
          # e.g. generate a relatively permissive schema
          #- "--skip-auto-generation=required,additionalProperties"
  - repo: https://github.com/jumanjihouse/pre-commit-hook-yamlfmt
    rev: 0.2.3  # or other specific tag
    hooks:
      - id: yamlfmt
        files: values.yaml
        args: [--mapping, '2', --sequence, '2', --offset, '0']
